# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_spk.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sid_lineEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sid_lineEdit.sizePolicy().hasHeightForWidth())
        self.sid_lineEdit.setSizePolicy(sizePolicy)
        self.sid_lineEdit.setReadOnly(True)
        self.sid_lineEdit.setObjectName("sid_lineEdit")
        self.verticalLayout.addWidget(self.sid_lineEdit)
        self.name_lineEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineEdit.sizePolicy().hasHeightForWidth())
        self.name_lineEdit.setSizePolicy(sizePolicy)
        self.name_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout.addWidget(self.name_lineEdit)
        self.gender_comboBox = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_comboBox.sizePolicy().hasHeightForWidth())
        self.gender_comboBox.setSizePolicy(sizePolicy)
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem("")
        self.gender_comboBox.addItem("")
        self.verticalLayout.addWidget(self.gender_comboBox)
        self.age_lineEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_lineEdit.sizePolicy().hasHeightForWidth())
        self.age_lineEdit.setSizePolicy(sizePolicy)
        self.age_lineEdit.setObjectName("age_lineEdit")
        self.verticalLayout.addWidget(self.age_lineEdit)
        self.prov_comboBox = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prov_comboBox.sizePolicy().hasHeightForWidth())
        self.prov_comboBox.setSizePolicy(sizePolicy)
        self.prov_comboBox.setObjectName("prov_comboBox")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.prov_comboBox.addItem("")
        self.verticalLayout.addWidget(self.prov_comboBox)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 100))
        self.saveButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancleButton = QtWidgets.QPushButton(self.frame)
        self.cancleButton.setMinimumSize(QtCore.QSize(0, 100))
        self.cancleButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cancleButton.setObjectName("cancleButton")
        self.horizontalLayout.addWidget(self.cancleButton)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "新的说话人"))
        self.name_lineEdit.setPlaceholderText(_translate("Dialog", "姓名"))
        self.gender_comboBox.setItemText(0, _translate("Dialog", "男"))
        self.gender_comboBox.setItemText(1, _translate("Dialog", "女"))
        self.age_lineEdit.setPlaceholderText(_translate("Dialog", "年龄"))
        self.prov_comboBox.setItemText(0, _translate("Dialog", "河北"))
        self.prov_comboBox.setItemText(1, _translate("Dialog", "山西"))
        self.prov_comboBox.setItemText(2, _translate("Dialog", "辽宁"))
        self.prov_comboBox.setItemText(3, _translate("Dialog", "吉林"))
        self.prov_comboBox.setItemText(4, _translate("Dialog", "黑龙江"))
        self.prov_comboBox.setItemText(5, _translate("Dialog", "江苏"))
        self.prov_comboBox.setItemText(6, _translate("Dialog", "浙江"))
        self.prov_comboBox.setItemText(7, _translate("Dialog", "安徽"))
        self.prov_comboBox.setItemText(8, _translate("Dialog", "福建"))
        self.prov_comboBox.setItemText(9, _translate("Dialog", "江西"))
        self.prov_comboBox.setItemText(10, _translate("Dialog", "山东"))
        self.prov_comboBox.setItemText(11, _translate("Dialog", "河南"))
        self.prov_comboBox.setItemText(12, _translate("Dialog", "湖北"))
        self.prov_comboBox.setItemText(13, _translate("Dialog", "湖南"))
        self.prov_comboBox.setItemText(14, _translate("Dialog", "广东"))
        self.prov_comboBox.setItemText(15, _translate("Dialog", "海南"))
        self.prov_comboBox.setItemText(16, _translate("Dialog", "四川"))
        self.prov_comboBox.setItemText(17, _translate("Dialog", "贵州"))
        self.prov_comboBox.setItemText(18, _translate("Dialog", "云南"))
        self.prov_comboBox.setItemText(19, _translate("Dialog", "陕西"))
        self.prov_comboBox.setItemText(20, _translate("Dialog", "甘肃"))
        self.prov_comboBox.setItemText(21, _translate("Dialog", "青海"))
        self.prov_comboBox.setItemText(22, _translate("Dialog", "台湾"))
        self.prov_comboBox.setItemText(23, _translate("Dialog", "内蒙古"))
        self.prov_comboBox.setItemText(24, _translate("Dialog", "广西"))
        self.prov_comboBox.setItemText(25, _translate("Dialog", "西藏"))
        self.prov_comboBox.setItemText(26, _translate("Dialog", "宁夏"))
        self.prov_comboBox.setItemText(27, _translate("Dialog", "新疆"))
        self.prov_comboBox.setItemText(28, _translate("Dialog", "北京"))
        self.prov_comboBox.setItemText(29, _translate("Dialog", "天津"))
        self.prov_comboBox.setItemText(30, _translate("Dialog", "上海"))
        self.prov_comboBox.setItemText(31, _translate("Dialog", "重庆"))
        self.prov_comboBox.setItemText(32, _translate("Dialog", "香港"))
        self.prov_comboBox.setItemText(33, _translate("Dialog", "澳门"))
        self.saveButton.setText(_translate("Dialog", "保存"))
        self.cancleButton.setText(_translate("Dialog", "取消"))
