# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1471, 1081)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sid_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sid_lineEdit.sizePolicy().hasHeightForWidth())
        self.sid_lineEdit.setSizePolicy(sizePolicy)
        self.sid_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sid_lineEdit.setReadOnly(True)
        self.sid_lineEdit.setObjectName("sid_lineEdit")
        self.horizontalLayout.addWidget(self.sid_lineEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.sname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sname_lineEdit.sizePolicy().hasHeightForWidth())
        self.sname_lineEdit.setSizePolicy(sizePolicy)
        self.sname_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sname_lineEdit.setReadOnly(True)
        self.sname_lineEdit.setObjectName("sname_lineEdit")
        self.horizontalLayout_8.addWidget(self.sname_lineEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 3)
        self.horizontalLayout_13.setStretch(2, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(0, 25))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.chn_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.chn_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.chn_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.chn_lineEdit.setReadOnly(True)
        self.chn_lineEdit.setObjectName("chn_lineEdit")
        self.gridLayout.addWidget(self.chn_lineEdit, 1, 2, 1, 1)
        self.play_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_Button.sizePolicy().hasHeightForWidth())
        self.play_Button.setSizePolicy(sizePolicy)
        self.play_Button.setMaximumSize(QtCore.QSize(120, 120))
        self.play_Button.setObjectName("play_Button")
        self.gridLayout.addWidget(self.play_Button, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.trans_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trans_lineEdit.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.trans_lineEdit.setFont(font)
        self.trans_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trans_lineEdit.setObjectName("trans_lineEdit")
        self.gridLayout.addWidget(self.trans_lineEdit, 0, 0, 1, 3)
        self.del_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_Button.sizePolicy().hasHeightForWidth())
        self.del_Button.setSizePolicy(sizePolicy)
        self.del_Button.setMaximumSize(QtCore.QSize(120, 120))
        self.del_Button.setObjectName("del_Button")
        self.gridLayout.addWidget(self.del_Button, 0, 4, 1, 1)
        self.record_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_Button.sizePolicy().hasHeightForWidth())
        self.record_Button.setSizePolicy(sizePolicy)
        self.record_Button.setMaximumSize(QtCore.QSize(120, 120))
        self.record_Button.setObjectName("record_Button")
        self.gridLayout.addWidget(self.record_Button, 0, 3, 1, 1)
        self.hackrf_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hackrf_lineEdit.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.hackrf_lineEdit.setFont(font)
        self.hackrf_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.hackrf_lineEdit.setReadOnly(True)
        self.hackrf_lineEdit.setObjectName("hackrf_lineEdit")
        self.gridLayout.addWidget(self.hackrf_lineEdit, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 25))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.rec_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.rec_tab.setObjectName("rec_tab")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.num_table = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_table.setFont(font)
        self.num_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.num_table.setObjectName("num_table")
        self.num_table.setColumnCount(7)
        self.num_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.num_table.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_10.addWidget(self.num_table)
        self.rec_tab.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.short_table = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.short_table.setFont(font)
        self.short_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.short_table.setObjectName("short_table")
        self.short_table.setColumnCount(7)
        self.short_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.short_table.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_11.addWidget(self.short_table)
        self.rec_tab.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.long_table = QtWidgets.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.long_table.setFont(font)
        self.long_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.long_table.setObjectName("long_table")
        self.long_table.setColumnCount(7)
        self.long_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.long_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.long_table)
        self.rec_tab.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.rec_tab)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.num_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_progressBar.setFont(font)
        self.num_progressBar.setProperty("value", 0)
        self.num_progressBar.setObjectName("num_progressBar")
        self.horizontalLayout_5.addWidget(self.num_progressBar)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.short_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.short_progressBar.setFont(font)
        self.short_progressBar.setProperty("value", 0)
        self.short_progressBar.setObjectName("short_progressBar")
        self.horizontalLayout_6.addWidget(self.short_progressBar)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.long_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.long_progressBar.setFont(font)
        self.long_progressBar.setProperty("value", 0)
        self.long_progressBar.setObjectName("long_progressBar")
        self.horizontalLayout_7.addWidget(self.long_progressBar)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1471, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_spk = QtWidgets.QAction(MainWindow)
        self.new_spk.setObjectName("new_spk")
        self.select_spk = QtWidgets.QAction(MainWindow)
        self.select_spk.setObjectName("select_spk")
        self.menu.addAction(self.new_spk)
        self.menu.addAction(self.select_spk)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.rec_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "说话人标识： "))
        self.label_8.setText(_translate("MainWindow", "说话人名称："))
        self.play_Button.setText(_translate("MainWindow", "播放"))
        self.label_9.setText(_translate("MainWindow", "频道："))
        self.del_Button.setText(_translate("MainWindow", "删除"))
        self.record_Button.setText(_translate("MainWindow", "录制"))
        self.hackrf_lineEdit.setText(_translate("MainWindow", "hackrf 未就绪"))
        item = self.num_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.num_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文本编号"))
        item = self.num_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文本内容"))
        item = self.num_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "频段"))
        item = self.num_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "设备"))
        item = self.num_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "时长"))
        item = self.num_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "(重新)录制"))
        self.rec_tab.setTabText(self.rec_tab.indexOf(self.widget), _translate("MainWindow", "数字"))
        item = self.short_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.short_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文本编号"))
        item = self.short_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文本内容"))
        item = self.short_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "频段"))
        item = self.short_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "设备"))
        item = self.short_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "时长"))
        item = self.short_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "(重新)录制"))
        self.rec_tab.setTabText(self.rec_tab.indexOf(self.tab_2), _translate("MainWindow", "短句"))
        item = self.long_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.long_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文本编号"))
        item = self.long_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文本内容"))
        item = self.long_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "频段"))
        item = self.long_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "设备"))
        item = self.long_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "时长"))
        item = self.long_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "(重新)录制"))
        self.rec_tab.setTabText(self.rec_tab.indexOf(self.tab), _translate("MainWindow", "长句"))
        self.label_5.setText(_translate("MainWindow", "数字："))
        self.label_6.setText(_translate("MainWindow", "短句："))
        self.label_7.setText(_translate("MainWindow", "长句："))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.new_spk.setText(_translate("MainWindow", "新建录制"))
        self.select_spk.setText(_translate("MainWindow", "已有录制"))
